[versions]
agp = "8.13.1"
appcompat = "1.7.1"
constraintLayout = "2.2.1"
core = "1.17.0"
coroutines = "1.10.2"
datastore = "1.2.0"
espresso = "3.7.0"
junit = "4.13.2"
kotlin = "2.2.21"
lifecycle = "2.10.0"
material = "1.13.0"
runner = "1.7.0"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
material = { module = "com.google.android.material:material", version.ref = "material" }

# architecture components
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

# kotlin
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

# testing
junit = { module = "junit:junit", version.ref = "junit" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

[plugins]
android-application = { id = "com.android.application" }
kotlin-android = { id = "kotlin-android" }

